### ISSUE TITLE
Is simplexml the best tool to be used here?

### ISSUE THREAD

**Issue by mudrd8mz** [lucisgit/moodle-qformat_qml#2]
In the comment at https://moodle.org/plugins/view/qformat_qml you mentioned that

> All of the sample files I was given to work with are all version 3, so it is built around that version.

But reading the QML v3 Overview spec at https://www.questionmark.com/us/qml/Pages/default.aspx there are things like:

> Attributes are defined in the form NAME=NUMBER, NAME=WORD or NAME=”STRING”.

or (from the examples):

> &lt;OUTCOME ID=”right” CONDITION=[”A”] SCORE=1>

Which is the syntax that simplexml will not understand as it always requires quotes. So, it seems to me that either a specific higher QML version should be required (4.x and 5.x seem to come with XSD), or a custom parser be implemented.

**Comment by T27M** [comment]
Thanks for taking the time to look at this, I am using V3 is due to the files being exported in that format from our (large) collection of question files that need to be migrated to Moodle. From all of the question files I have used so far featuring multiple question types, with different node attributes, I have yet to encounter any issue reading the attributes from the nodes. 

Here are some examples of what I've been dealing with: https://www.dropbox.com/s/zgbczj1poaepj4c/QML%20Question%20Files.zip?dl=0

I'll have a look at this in further detail shortly along with the other issue you raised.

**Comment by mudrd8mz** [comment]
No worries. If it works well for real questions you deal with, I do not think anything has to change just because of 10 years old vague specs. Overall, the more modern versions of the QML seem to have more strict XML format. Feel free to close this - I was just wondering. Thanks for the info.
